### ISSUE TITLE
Logo design for linux-utils

### ISSUE THREAD

**Issue by zuurw** [remipassmoilesel/linux-utils#1]
Hi , my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by remipassmoilesel** [comment]
Hi, this project is a small toolbox for nerds, I don't if it need a fancy logo :)

**Comment by zuurw** [comment]
Hi @remipassmoilesel , this project is the same of the sharemusic???

Best regards!

**Comment by remipassmoilesel** [comment]
No it's not, it a bunch of scripts for linux.

**Comment by remipassmoilesel** [comment]
Have a good day !
